//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up10_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Name { get; set; }
        public string Art { get; set; }
        public Nullable<double> MinPrice { get; set; }
    
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
