//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up10_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDefect
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Coefficent { get; set; }
    }
}
